### ISSUE TITLE
"pick and place" file

### ISSUE THREAD

**Issue by jantyikt** [Darmur/tubeamp#1]
Maybe you could add a "pick and place" file to the project? I would like to order a pcb with assembly, for that I would need to provide to the pcb manufacturer (pcbways). I suppose I could somehow reproduce it from the gerber files...  it'd be great if I didn't have to, but had this attached to the project. (I'm a noob at this point in time, but I'm trying to learn from the example of this project.)

**Comment by Darmur** [comment]
the pick&place files are required for SMD components, this design has only through-hole ones. even if I generate the pick&place file, it will be empty

**Comment by jantyikt** [comment]
Hm, I see. Thank you very much for the information!
